# load necessary packages
library(ggplot2)
library(mvtnorm)

# define wrapper functions from class (used to generate data for one category)
sigmaXY <- function(rho, sdX, sdY) {
    covTerm <- rho * sdX * sdY
    VCmatrix <- matrix(c(sdX^2, covTerm, covTerm, sdY^2), 
                       2, 2, byrow = TRUE)
    return(VCmatrix)
}

genBVN <- function(n = 1, seed = NA, muXY=c(0,1), sigmaXY=diag(2)) {
    if(!is.na(seed)) set.seed(seed)
    rdraws <- rmvnorm(n, mean = muXY, sigma = sigmaXY)
    return(rdraws)
}


# function generates 2D data for two categories 
# -- Cat1: X,Y data generated by a bivariate normal distribution 
# -- Cat2: linear X,Y relationship plus a normally distributed random error
genData <- function(noCat1=100, muCat1=c(5,5), sdCat1=c(2,1), rhoCat1=0.5, 
                    noCat2=100, minXCat2=0, maxXCat2=10, slopeCat2=0.9, 
                    seed=1111, writeCSV = TRUE, plotPDF = TRUE) {
    
    # generate category 1 data
    sigmaCat1 <- sigmaXY(rhoCat1, sdCat1[1], sdCat1[2])
    cat1 <- genBVN(noCat1, seed, muCat1, sigmaCat1)
    
    # generate category 2 data
    set.seed(seed + 1)
    cat2_X <- runif(noCat2, min = minXCat2, max = maxXCat2)
    cat2_Y <- slopeCat2 * cat2_X + rnorm(noCat2, 0, 0.5) 
    cat2 <- cbind(cat2_X, cat2_Y)
    
    # combine data and add binary outcome and labels
    Df <- as.data.frame(rbind(cat1, cat2))
    catLabel <- c(rep("category1", noCat1), rep("category2", noCat2))
    target <- c(rep(0, noCat1), rep(1, noCat2))
    Df <- data.frame(Df, catLabel, target)
    colnames(Df) <- c("X1", "X2", "catLabel", "target")
    
    # plot data
    if (plotPDF == TRUE) {
        ggplot(data = Df, aes(x = X2, y = X1, colour = catLabel, fill = catLabel)) +
            geom_point() +
            xlab("X2") +
            ylab("X1") + 
            theme_bw() #+
            #theme(text=element_text(family="Arial"))
        ggsave("dataPlot.pdf", scale = 1, width = 4, height = 4)
    }
    
    # write dataset to csv file
    if (writeCSV == TRUE ) {
        write.csv(Df, file = "dataset.csv")
    }
    return(Df)
}

# call function using default values
genData()
